"""A guard test may not opt out of guarding.

Review 7 found tests that pass by not running. The pattern was always the same: a test reads a
report, and skips itself if the report is not there. Every one of those reports is committed, so
the skip was unreachable in a normal checkout -- and would fire, silently, in exactly the situation
where the guard matters: someone deleted or failed to regenerate the artefact the claim rests on.

This file is the meta-guard. It does not test the pipeline; it tests the tests.
"""
import glob, json, os, re, subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TESTS = sorted(glob.glob(os.path.join(ROOT, "tests", "test_*.py")))
SELF = os.path.basename(__file__)


def _tracked():
    """Repo-relative report paths git knows about. Falls back to what is on disk outside a clone."""
    try:
        out = subprocess.run(["git", "ls-files", "reports"], cwd=ROOT,
                             capture_output=True, text=True, timeout=30)
        if out.returncode == 0 and out.stdout.strip():
            return set(out.stdout.split())
    except (OSError, subprocess.SubprocessError):
        pass
    return {os.path.relpath(p, ROOT)
            for p in glob.glob(os.path.join(ROOT, "reports", "**", "*"), recursive=True)
            if os.path.isfile(p)}


def test_no_test_skips_itself_because_a_committed_report_is_absent():
    tracked = {os.path.basename(p) for p in _tracked() if p.endswith(".json")}
    assert tracked, "could not determine which reports are committed; this test would pass vacuously"
    bad = []
    for f in TESTS:
        if os.path.basename(f) == SELF:
            continue
        for m in re.finditer(r"pytest\.skip\(\s*f?[\"']([^\"']*)[\"']", open(f).read()):
            for tok in re.findall(r"[\w.]+\.json", m.group(1)):
                if tok in tracked:
                    bad.append(f"{os.path.basename(f)}: skips on missing {tok}, which is committed")
    assert not bad, "assert the file is present instead of skipping:\n" + "\n".join(bad)


def test_the_committed_reports_are_actually_present():
    """The other half: the assertions added above are only meaningful if the files really ship."""
    missing = [n for n in _tracked() if not os.path.exists(os.path.join(ROOT, n))]
    assert not missing, f"tracked reports absent from the working tree: {sorted(missing)}"


def test_every_test_file_defines_at_least_one_test():
    """A file of helpers with no test function is collected, passes, and asserts nothing."""
    empty = [os.path.basename(f) for f in TESTS
             if not re.search(r"^\s*def test_", open(f).read(), re.M)]
    assert not empty, f"no test functions in: {empty}"


# The one skip this suite is allowed to have, and why. Adding to this list is a deliberate act.
ALLOWED_SKIPS = 1
ALLOWED_SKIPS_REASON = """
tests/test_review4_wash_null_baselines.py: experiments/pairs was regenerated by EXP_0038 and
experiments/pairs_wash was not, and pairs_wash/provenance.json predates the pipeline_sha256 field
entirely -- so there is genuinely no way to tell whether the same code produced both batches. The
comparison is meaningless until both are re-run with tools/run_pairs_batch.py, which needs a full
segmentation pass. Skipping is the honest answer here; being silent about it was not.
"""


def test_the_number_of_skipped_tests_has_not_grown():
    """reports/suite.json records what the last verify.py run actually did. A new skip means a guard
    stopped running, and this is where that has to be argued for rather than absorbed.

    The file is written after pytest finishes, so a newly-introduced skip is caught on the NEXT
    verify run, not the one that introduces it. That is a one-run delay, not a hole: the number is
    committed, so the delay is visible in the diff."""
    p = os.path.join(ROOT, "reports", "suite.json")
    assert os.path.exists(p), "reports/suite.json is missing; run tools/verify.py"
    s = json.load(open(p))
    assert s["skipped"] <= ALLOWED_SKIPS, (
        f"{s['skipped']} tests skipped, {ALLOWED_SKIPS} allowed. A skip is a guard that stopped "
        f"running -- fix it or extend ALLOWED_SKIPS with a reason.\n{ALLOWED_SKIPS_REASON}")
    # deliberately NOT asserting s["failed"] == 0. verify.py's exit code already covers that, and
    # asserting it here is a deadlock: one failing run records failed >= 1, which fails this test on
    # the next run, which keeps the count at >= 1 forever. Committed counts can only be used for
    # quantities a passing run is free to change.
