#!/usr/bin/env python3
"""Turn a LOCALLY-HELD copy of the EditGarment dataset into provenance records that can never be
mistaken for physical evidence.

EditGarment is a garment-EDITING dataset: the "after" image is generated by an image model from the
"before" image. That makes it useful for exactly one thing here (instruction/appearance priors) and
useless -- worse than useless, actively misleading -- for the thing this repository actually claims
to measure. Every physical number in this project (fringe depth after a wash, how a raw edge frays,
where a hem lands once the garment has been cut) is a claim about cloth. A generated "after" image is
a claim about a model's prior over pixels. Scoring a prediction against one and reporting the result
next to a real before/after pair is how a repository ends up believing it has validated physics when
it has validated a renderer. So every record this adapter emits is stamped, unconditionally:

    pair_type                          = "synthetic_edit"
    excluded_from_physical_evaluation  = true
    exact_garment                      = "known_different"

`exact_garment` is the tri-state used across this repository's provenance records, and for a
synthetic edit the honest value is `known_different`, not `not_verified`. `not_verified` means "we
have not established identity yet" -- it leaves open that some later check could promote the record
to `verified`. Nothing could. The edited frame is not a photograph of a second garment, nor of the
first garment after a real cut; the pixels showing the shortened leg were never cloth at all. Saying
`not_verified` would file a permanent impossibility as a pending task. `known_different` closes it.

Three things this tool deliberately does NOT do, because doing them would be the whole defect:

  * It does not download anything. There is no URL constant, no network import, no fetch path, and
    no default `--root`. `tests/test_editgarment_adapter.py` asserts that statically, so a later
    "convenience" fetch cannot be added quietly.
  * It does not automate, script around, or bypass the dataset's access-controlled release process.
    A human obtains the files under that process; this tool reads what is already on their disk.
  * It does not emit anything at all until the caller states, explicitly, that they hold that access
    (`--i-have-dataset-access`, or DENIMTWIN_EDITGARMENT_ACCESS=1). Refusal is the DEFAULT, and it
    exits non-zero, because a rights acknowledgement that is on by default acknowledges nothing.

It also refuses to write into the repository's tracked artefact trees. Records derived from a gated
dataset belong in a scratch directory the caller names, not in `data/`, `reports/` or `experiments/`
where the next `git add -A` would sweep them into a public repository.

Layout it expects under --root (see docs/EDITGARMENT.md for the full description):

    <root>/editgarment_manifest.json     written by the user from their access grant
    <root>/images/<sample_id>_source.png  } paths are relative to <root> and must stay inside it
    <root>/images/<sample_id>_edited.png  }

Usage:

    tools/editgarment_adapter.py --root /path/outside/this/repo/editgarment \
        --out /path/to/scratch/editgarment_records.jsonl --i-have-dataset-access

Exit codes: 0 emitted; 2 refused for want of the rights acknowledgement; 3 the local files are not
the shape this adapter accepts (nothing is written in either non-zero case).
"""
import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]

DATASET = "EditGarment"
MANIFEST_NAME = "editgarment_manifest.json"
ACCESS_FLAG = "--i-have-dataset-access"
ACCESS_ENV = "DENIMTWIN_EDITGARMENT_ACCESS"
DOC = "docs/EDITGARMENT.md"

EXIT_OK = 0
EXIT_NO_ACCESS_ACK = 2
EXIT_BAD_INPUT = 3

PAIR_TYPE = "synthetic_edit"
EXACT_GARMENT = "known_different"
EXCLUSION_REASON = (
    "the edited frame is generated, not photographed: it is evidence about an image model's prior, "
    "not about how a garment behaves when it is cut and washed"
)
EXACT_GARMENT_REASON = (
    "the edited frame depicts no physical garment, so identity with the source garment can never be "
    "verified -- 'not_verified' would file an impossibility as a pending check"
)

#: Every rights field a record must carry. No value is invented by this tool; each is copied from
#: the manifest the user wrote out of their own access grant.
RIGHTS_FIELDS = ("license_id", "license_url", "license_statement", "attribution", "rights_holder",
                 "redistributable", "derivatives_allowed", "commercial_use_allowed")
RIGHTS_BOOLS = ("redistributable", "derivatives_allowed", "commercial_use_allowed")
DATASET_FIELDS = ("source_url", "retrieved_at", "generation_method")
SAMPLE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}")

#: Trees whose contents are committed. A gated dataset's derivatives never land in one of them.
TRACKED_TREES = ("data", "reports", "experiments", "docs", "protocol", "models")

ACCESS_REFUSAL = f"""REFUSED: no dataset-access acknowledgement.

{DATASET} is distributed under an access-controlled process. This repository does not distribute the
dataset, does not mirror it, and does not automate, script around or bypass that process -- there is
no download path in this tool at all.

If you have already obtained the files yourself under the dataset's official access process (the
authors' request form and usage agreement, as published on their official release page) and they are
sitting on your disk, re-run with:

    {ACCESS_FLAG}          (or set {ACCESS_ENV}=1)

which states that you hold that access and accept the terms it was granted under. Refusing is the
default on purpose: an acknowledgement that is on by default acknowledges nothing.

If you have not obtained it: go through the dataset's official access process first. Nothing in this
repository will do that for you.

See {DOC}."""


def _err(msg):
    print(f"REFUSED: {msg}", file=sys.stderr)


def has_access_ack(flag, env):
    """The acknowledgement is opt-in twice over: an explicit flag, or an env var set to exactly 1."""
    return bool(flag) or env.get(ACCESS_ENV, "") == "1"


def out_path_refusal(out):
    """Why this output path is not allowed, or None. Keeps gated derivatives out of tracked trees."""
    resolved = Path(out).resolve()
    for tree in TRACKED_TREES:
        base = (ROOT / tree).resolve()
        if resolved == base or base in resolved.parents:
            return (f"--out {out} is inside the repository's tracked {tree}/ tree. Records derived "
                    f"from a gated dataset must not be written where they can be committed; give a "
                    f"path outside {ROOT}.")
    return None


def _rel_inside(root, rel, field):
    """Resolve a manifest-relative path, refusing absolute paths and anything that escapes root."""
    if not isinstance(rel, str) or not rel.strip():
        return None, f"{field} is missing or empty"
    p = Path(rel)
    if p.is_absolute():
        return None, f"{field}={rel!r} is absolute; manifest paths must be relative to --root"
    full = (root / p).resolve()
    if root.resolve() not in full.parents:
        return None, f"{field}={rel!r} escapes --root"
    if not full.is_file():
        return None, f"{field}={rel!r} does not exist under --root"
    return full, None


def _image_facts(full, field):
    """Derived NUMBERS only: dimensions and a digest. No pixel ever leaves the caller's disk."""
    try:
        with Image.open(full) as im:
            im.verify()
        with Image.open(full) as im:
            width, height = im.size
            mode = im.mode
            fmt = im.format
    except Exception as exc:                      # PIL raises a zoo of types for broken files
        return None, f"{field}={full.name!r} is not a readable image ({type(exc).__name__})"
    if width < 1 or height < 1:
        return None, f"{field}={full.name!r} has a degenerate size {width}x{height}"
    digest = hashlib.sha256(full.read_bytes()).hexdigest()
    return {"width": width, "height": height, "mode": mode, "format": fmt, "sha256": digest}, None


def read_manifest(root, manifest_name):
    """Load the manifest. Returns (obj, errors)."""
    path = root / manifest_name
    if not root.is_dir():
        return None, [f"--root {root} is not a directory"]
    if not path.is_file():
        return None, [f"no {manifest_name} under --root {root}; see {DOC} for the expected layout"]
    try:
        obj = json.loads(path.read_text())
    except (ValueError, UnicodeDecodeError) as exc:
        return None, [f"{manifest_name} is not valid JSON: {exc}"]
    if not isinstance(obj, dict):
        return None, [f"{manifest_name} must be a JSON object, got {type(obj).__name__}"]
    return obj, []


def check_dataset_block(manifest):
    """Dataset-level rights and provenance. Returns (rights, provenance_bits, errors)."""
    errors = []
    rights_in = manifest.get("rights")
    rights = {}
    if not isinstance(rights_in, dict):
        errors.append("manifest has no 'rights' object; copy the terms of your access grant into it")
    else:
        for field in RIGHTS_FIELDS:
            if field not in rights_in:
                errors.append(f"rights.{field} is missing")
                continue
            value = rights_in[field]
            if field in RIGHTS_BOOLS:
                if not isinstance(value, bool):
                    errors.append(f"rights.{field} must be true or false, got {value!r}")
                    continue
            elif not isinstance(value, str) or not value.strip():
                errors.append(f"rights.{field} must be a non-empty string")
                continue
            rights[field] = value
        if rights.get("license_url") and not str(rights["license_url"]).startswith(("http://", "https://")):
            errors.append("rights.license_url must be an http(s) URL")
        # data/schemas/provenance.schema.json closes license_id to SPDX identifiers, two sentinels,
        # and SPDX's own LicenseRef- form for a bespoke written agreement. A gated dataset's usage
        # agreement is precisely the last of those, so a free-text id like
        # "editgarment-research-use-agreement" is carried across as LicenseRef-... rather than
        # rejected -- and the operator's original string is kept verbatim in license_statement,
        # which is the audit trail the schema asks that field to be. Nothing is invented: the
        # normalisation is a spelling change with the original preserved beside it.
        lid = str(rights.get("license_id", "")).strip()
        if lid and not (lid in ("ALL-RIGHTS-RESERVED", "UNDETERMINED")
                        or lid.startswith(("CC", "GFDL", "LicenseRef-"))):
            safe = re.sub(r"[^A-Za-z0-9.-]+", "-", lid).strip("-")[:60] or "dataset-agreement"
            rights["license_id"] = f"LicenseRef-{safe}"
            rights.setdefault("license_statement", lid)
        if rights.get("redistributable") is True:
            errors.append(
                "rights.redistributable is true. This adapter is for an access-controlled dataset "
                "and will not emit records asserting a right to redistribute it; if your grant "
                "really permits redistribution, that is a different dataset than the one this "
                "adapter is written for.")
    bits = {}
    for field in DATASET_FIELDS:
        value = manifest.get(field)
        if not isinstance(value, str) or not value.strip():
            errors.append(f"manifest.{field} is missing or empty")
            continue
        bits[field] = value.strip()
    if bits.get("source_url") and not bits["source_url"].startswith(("http://", "https://")):
        errors.append("manifest.source_url must be the http(s) page you obtained access through")
    if bits.get("retrieved_at") and not DATE_RE.match(bits["retrieved_at"]):
        errors.append("manifest.retrieved_at must start with an ISO date, YYYY-MM-DD")
    return rights, bits, errors


def build_records(root, manifest, limit):
    """Validate every sample and turn it into a record. Returns (records, errors)."""
    rights, bits, errors = check_dataset_block(manifest)
    samples = manifest.get("samples")
    if not isinstance(samples, list) or not samples:
        errors.append("manifest.samples must be a non-empty list")
        samples = []
    if limit:
        samples = samples[:limit]
    records, seen = [], set()
    for i, sample in enumerate(samples):
        where = f"samples[{i}]"
        if not isinstance(sample, dict):
            errors.append(f"{where} is not an object")
            continue
        sid = sample.get("sample_id")
        if not isinstance(sid, str) or not SAMPLE_ID_RE.match(sid):
            errors.append(f"{where}.sample_id={sid!r} is missing or not [A-Za-z0-9._-] (max 64)")
            continue
        if sid in seen:
            errors.append(f"{where}.sample_id={sid!r} is a duplicate; record ids must be unique")
            continue
        seen.add(sid)
        instruction = sample.get("instruction")
        if not isinstance(instruction, str) or len(instruction.strip()) < 4:
            errors.append(f"{where}.instruction is missing or too short to describe an edit")
            continue
        images, bad = {}, False
        for field, key in (("source_image", "source_image"), ("edited_image", "edited_image")):
            full, why = _rel_inside(root, sample.get(field), f"{where}.{field}")
            if why:
                errors.append(why)
                bad = True
                continue
            facts, why = _image_facts(full, f"{where}.{field}")
            if why:
                errors.append(why)
                bad = True
                continue
            images[key] = {"path_relative_to_root": sample[field], **facts}
        if bad:
            continue
        # The shape here is data/schemas/provenance.schema.json's, exactly, and that is the point.
        # The first version of this adapter emitted its own field names -- excluded_from_physical_
        # evaluation, exclusion_reason, exact_garment_reason, a `sample` block -- which read
        # perfectly well to a human and were rejected by tools/validate_provenance.py as
        # "Additional properties are not allowed". So the exclusion these records exist to carry was
        # enforced by nothing: the project's own gate could not read them at all. A label only
        # excludes a sample if the thing doing the excluding can parse it.
        rec = {
            # namespace:id, as data/schemas/provenance.schema.json requires of every record,
              # so an EditGarment sample can never collide with a harvested image or a found pair.
              "record_id": f"editgarment:{sid}",
            "sample_kind": "before_after_pair",
            # Unconditional, not derived from the input: a file cannot talk this adapter into
            # emitting a record that reads as physical evidence.
            "pair_type": PAIR_TYPE,
            "exact_garment": EXACT_GARMENT,
            "exact_garment_basis": EXACT_GARMENT_REASON,
            "rights": {k: rights[k] for k in RIGHTS_FIELDS if k in rights},
            "provenance": {
                "source": DATASET,
                "source_url": bits.get("source_url"),
                "retrieved_at": bits.get("retrieved_at"),
                "method": (f"local adapter tools/editgarment_adapter.py over a copy of {DATASET} "
                           f"obtained by the operator under the dataset's own access process; "
                           f"edited frames were produced by {bits.get('generation_method')}"),
                "recorded_in": "tools/editgarment_adapter.py",
                "local_path": images["source_image"]["path_relative_to_root"],
                "notes": EXCLUSION_REASON,
            },
            "synthetic": {
                "generator": str(bits.get("generation_method") or DATASET),
                "edit_description": instruction.strip(),
            },
            "sample": {
                "sample_id": sid,
                "instruction": instruction.strip(),
                "edit_type": sample.get("edit_type"),
                "source_image": images["source_image"],
                "edited_image": images["edited_image"],
            },
        }
        # No self-asserted training_eligible: the rule in tools/validate_provenance.py derives it,
        # and for pair_type synthetic_edit it derives False unconditionally. That is the exclusion,
        # in the one place that enforces it.
        records.append(rec)
    if errors:
        return [], errors
    return records, []


def write_records(records, out, fmt):
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "jsonl":
        out.write_text("".join(json.dumps(r, sort_keys=True) + "\n" for r in records))
    else:
        out.write_text(json.dumps(records, indent=1, sort_keys=True) + "\n")
    return out


def main(argv=None, env=None):
    env = os.environ if env is None else env
    ap = argparse.ArgumentParser(
        description=(f"Emit provenance records from a LOCAL copy of the access-controlled {DATASET} "
                     f"dataset. Downloads nothing; refuses by default. See {DOC}."),
        epilog=("Every emitted record is pair_type=synthetic_edit and is excluded from "
                "physical-accuracy evaluation: a generated 'after' image is not evidence about "
                "cloth."))
    ap.add_argument("--root", required=True,
                    help="local directory holding files you already obtained under the dataset's "
                         "own access process. There is no default and nothing is ever fetched.")
    ap.add_argument("--out", required=True,
                    help="file to write; must be outside the repository's tracked trees")
    ap.add_argument(ACCESS_FLAG, dest="access_ack", action="store_true",
                    help=f"state that you hold access to {DATASET} under its official process and "
                         f"accept its terms. Without this (or {ACCESS_ENV}=1) the tool refuses.")
    ap.add_argument("--manifest", default=MANIFEST_NAME,
                    help=f"manifest file name inside --root (default: {MANIFEST_NAME})")
    ap.add_argument("--format", choices=("jsonl", "json"), default="jsonl",
                    help="jsonl (one record per line, default) or a JSON array")
    ap.add_argument("--limit", type=int, default=0, help="emit at most N samples (0 = all)")
    ap.add_argument("--overwrite", action="store_true",
                    help="allow --out to replace an existing file")
    a = ap.parse_args(argv)

    if not has_access_ack(a.access_ack, env):
        print(ACCESS_REFUSAL, file=sys.stderr)
        return EXIT_NO_ACCESS_ACK

    why = out_path_refusal(a.out)
    if why:
        _err(why)
        return EXIT_BAD_INPUT
    if Path(a.out).exists() and not a.overwrite:
        _err(f"--out {a.out} already exists; pass --overwrite to replace it")
        return EXIT_BAD_INPUT
    if a.limit < 0:
        _err(f"--limit {a.limit} is negative")
        return EXIT_BAD_INPUT

    root = Path(a.root).expanduser()
    manifest, errors = read_manifest(root, a.manifest)
    if not errors:
        records, errors = build_records(root, manifest, a.limit)
    if errors:
        _err(f"{len(errors)} problem(s) in the local {DATASET} copy at {root}; nothing was written:")
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return EXIT_BAD_INPUT

    written = write_records(records, a.out, a.format)
    print(json.dumps({
        "dataset": DATASET,
        "root": str(root.resolve()),
        "out": str(written),
        "format": a.format,
        "records": len(records),
        "pair_type": PAIR_TYPE,
        "excluded_from_physical_evaluation": True,
        "note": f"synthetic edits: usable as appearance/instruction priors only. {EXCLUSION_REASON}.",
    }, indent=1))
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
