#!/usr/bin/env python3
"""Generate the printable pilot documents FROM the shot plan, so they cannot drift from it.

A runbook typed by hand is a second copy of the capture list, and the moment a shot is added to the
specification the two disagree. The person following the paper then collects a different set of
evidence from the one the gate requires, discovers it at the gate, and has a garment on the table.

So every document here is derived: the runbook follows the same ordering the app follows, because it
calls the same `plan.order`; the measurement sheet lists what `gates.REQUIRED_MEASUREMENTS` requires;
the rig checklist lists what `gates.REQUIRED_SETUP_CHECKS` requires. `--check` fails if any of them
is out of date, and tools/verify.py runs it.

    tools/make_runbook.py [--write] [--check] [--out protocol/pilot]
"""
import argparse
import sys
import textwrap
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from denimtwin.pilot import cutspec as CUT      # noqa: E402
from denimtwin.pilot import gates as GATES      # noqa: E402
from denimtwin.pilot import hem as HEM          # noqa: E402
from denimtwin.pilot import plan as PLAN        # noqa: E402
from denimtwin.pilot import qa as QA            # noqa: E402
from denimtwin.pilot import spec as SPEC        # noqa: E402

BANNER = ("<!-- generated by tools/make_runbook.py from protocol/shotplan/shotplan.json. "
          "Do not edit by hand: run the tool. -->")


def wrap(s, width=94, indent=""):
    return "\n".join(textwrap.fill(line, width, initial_indent=indent,
                                   subsequent_indent=indent) or indent
                     for line in str(s).split("\n"))


def fmt_time(seconds):
    m = int(round(seconds / 60.0))
    return "%d h %02d min" % (m // 60, m % 60) if m >= 60 else "%d min" % m


def all_present_answers(spec):
    """The most demanding garment: every feature present, one instance of each counted thing."""
    return {f["key"]: (1 if f["type"] == "count" else True) for f in spec.features}


def build(spec):
    answers = all_present_answers(spec)
    shots, meta = PLAN.activate(spec, answers, {"leg_opening_cm": {"mean": 20.0}})
    ordered = PLAN.order(spec, shots)
    return shots, ordered


# --------------------------------------------------------------------------------------------

def doc_runbook(spec, shots, ordered):
    out = [BANNER, "# Pilot Capture Runbook", "",
           wrap("This follows the exact order the app gives you, because it is generated from the "
                "same ordering code. Working down this page and working through the app's NEXT "
                "ACTION are the same sequence: front-facing frames before the garment is turned "
                "over, everything that shares a camera height and lens together, all the ruler "
                "macros in one run, and the required re-lays kept apart because they are the "
                "measurement rather than an overhead."), "",
           wrap("Times are the specification's DECLARED planning figures. Nobody has yet timed this "
                "rig, and the app replaces them with your own measured pace once it has three "
                "observations of a step class. Treat the totals as an order of magnitude."), ""]
    by_state = {}
    for e in ordered:
        by_state.setdefault(e["state"], []).append(e)
    order_of = {s["state"]: s["order"] for s in spec.states}
    label_of = {s["state"]: s["label"] for s in spec.states}

    out += ["## What the whole pilot comes to", "",
            "| state | frames | required | declared time |", "|---|---|---|---|"]
    for st in sorted(by_state, key=lambda k: order_of.get(k, 99)):
        es = by_state[st]
        req = [e for e in es if e["necessity"] != "optional"]
        out.append("| %s | %d | %d | %s |"
                   % (label_of.get(st, st), len(es), len(req),
                      fmt_time(PLAN.estimate_seconds(spec, es))))
    out.append("| **total** | **%d** | **%d** | **%s** |"
               % (len(ordered), len([e for e in ordered if e["necessity"] != "optional"]),
                  fmt_time(PLAN.estimate_seconds(spec, ordered))))
    out += ["", wrap("That total is the most demanding garment the plan can describe: every "
                     "optional feature present and one instance of each. A plain pair with no "
                     "paint, no repairs and no coin pocket is materially shorter, and the app "
                     "tells you your own number after intake."), ""]

    cur = None
    for e in ordered:
        grp = (e["state"], PLAN.ORIENTATION.get(e["garment_side"], "either"),
               e["relay_generation"], e.get("camera_height_group"), e.get("lens"))
        if grp != cur:
            cur = grp
            out += ["", "### %s — %s, lay %d, %s, %s lens"
                    % (label_of.get(e["state"], e["state"]),
                       {"front_up": "FRONT up", "back_up": "BACK up",
                        "either": "either face"}[grp[1]], grp[2], grp[3], grp[4]), ""]
        bits = []
        if e.get("needs_relay_before"):
            bits.append("**LIFT AND RE-LAY FIRST**")
        if e.get("needs_camera_reposition_before"):
            bits.append("**TAKE THE PHONE OFF THE MOUNT AND REMOUNT IT**")
        if e.get("needs_second_person"):
            bits.append("**NEEDS A SECOND PERSON**")
        out.append("- [ ] `%s` (%d/%d, %s%s)%s"
                   % (e["shot_id"], e["rep"], e["rep_of"], e["necessity"],
                      ", " + e["conditional_on"] if e.get("conditional_on") else "",
                      "  " + " ".join(bits) if bits else ""))
        out.append(wrap(e["framing"], 90, "      "))
        out.append("      *why:* " + e["purpose"].replace("\n", " "))
    return "\n".join(out) + "\n"


def doc_equipment(spec, shots, ordered):
    lenses = sorted({e.get("lens") for e in ordered if e.get("lens")})
    heights = sorted({e.get("camera_height_group") for e in ordered if e.get("camera_height_group")})
    return "\n".join([BANNER, "# Equipment checklist", "",
        wrap("Everything below is implied by a shot in the plan. The lens and camera-height groups "
             "are the ones the ordering actually batches by, so a missing one is a whole block of "
             "the session you cannot shoot."), "",
        "- [ ] Phone with a locked-exposure camera app and these lenses: **%s**" % ", ".join(lenses),
        "- [ ] Overhead mount or copy stand that holds the phone still and level",
        "- [ ] Camera positions needed: %s" % ", ".join(heights),
        "- [ ] Printed ChArUco board, **8 x 11 squares at 25.0 mm**, printed at 100% scale "
        "(no 'fit to page'), mounted flat and rigid",
        "- [ ] Steel rule with millimetre graduations, for verifying the printed board",
        "- [ ] A second rule or loop tape that can lie flat beside a hem",
        "- [ ] Tape measure for the garment measurements",
        "- [ ] Vernier or dial caliper for fabric thickness",
        "- [ ] Kitchen scale reading to 1 g for garment and offcut mass",
        "- [ ] Matte, non-reflective backdrop, dark and saturated (a dark green works; light-wash "
        "denim on a light backdrop is hard to segment)",
        "- [ ] Two diffuse lights at about 45 degrees",
        "- [ ] Grey or white reference card",
        "- [ ] Fabric shears, sharp, and a straightedge long enough to span a leg",
        "- [ ] Tailor's chalk or a fine marker that will not bleed",
        "- [ ] Two labels for the offcuts, written before cutting",
        "- [ ] A second person available for the cut-mark verification",
        "- [ ] A way to block daylight, or a room without it", ""])


def doc_rig(spec, shots, ordered):
    lines = [BANNER, "# Rig setup checklist", "",
             wrap("Every reading here is recorded by `tools/pilot.py setup`, and the cut gate "
                  "refuses to open until all of them exist and pass. They are properties of the "
                  "rig, not of the garment: freeze them once and every capture in the session "
                  "carries the hash of this configuration."), "", "## The frozen configuration", "",
             "- [ ] Camera model recorded",
             "- [ ] Mount height above the surface measured and recorded (cm)",
             "- [ ] Lens chosen for whole-garment frames and locked",
             "- [ ] Backdrop identified, and it will not change during the session",
             "- [ ] Lighting model and setting recorded",
             "- [ ] The frozen gap between the legs decided and recorded (cm)",
             "- [ ] Exposure and white balance locked",
             "- [ ] Room recorded", "", "## The calibration readings", ""]
    why = {
        "empty_backdrop": "a frame of the backdrop with nothing on it, so a mark on the cloth can "
                          "later be told from a mark on the garment",
        "board_verification": "the board photographed and detected, so the detector is known to "
                              "work on this print under this light",
        "board_square_measured": "a run of squares measured with a steel rule. The board declares "
                                 "25.0 mm; a printer that scaled to 95% puts that error into every "
                                 "measurement in the study",
        "lighting_test": "no hotspot or shadow across the area the garment will occupy",
        "exposure_white_balance": "a grey or white card photographed with the locked settings, so "
                                  "colour change through washing has a reference",
        "camera_height": "measured and recorded, because it sets the scale and the depth of field",
        "lens_selection": "chosen and locked; changing lens mid-session changes the geometry",
        "backdrop_identified": "named, so a change of backdrop is a recorded deviation",
        "daylight_controlled": "daylight excluded or constant. A session that starts at noon and "
                               "ends at dusk has two colour temperatures in it",
        "board_garment_coplanar": "a low-angle frame showing the board and the garment on one "
                                  "surface. If the board sits on a book, every scale is wrong by "
                                  "the thickness of the book",
    }
    for c in GATES.REQUIRED_SETUP_CHECKS:
        lines.append("- [ ] **%s** — %s" % (c, why.get(c, "")))
    lines += ["", wrap("The board's squares must measure %.1f mm within %.1f mm. Measure a run of "
                       "eight and divide: a single square is too short to read to that precision."
                       % (GATES.BOARD_SQUARE_MM, GATES.BOARD_SQUARE_TOLERANCE_MM)), ""]
    return "\n".join(lines)


def doc_anatomy(spec, shots, ordered):
    lines = [BANNER, "# Anatomical shot list", "",
             wrap("Every region the plan can ask for, and the frames that cover it. Regions marked "
                  "*conditional* only appear if you answered that the feature is present; a "
                  "question you have not answered is treated as PRESENT, so the frame is planned "
                  "rather than dropped."), ""]
    by_group = {}
    for r in spec.regions:
        by_group.setdefault(r["group"], []).append(r)
    shots_by_region = {}
    for e in ordered:
        shots_by_region.setdefault(e.get("region_id"), []).append(e)
    for grp in sorted(by_group):
        lines += ["", "## %s" % grp.replace("_", " "), "",
                  "| region | side | frames | changes with cut / wash |", "|---|---|---|---|"]
        for r in sorted(by_group[grp], key=lambda x: x["region_id"]):
            es = shots_by_region.get(r["region_id"], [])
            lines.append("| `%s` %s | %s | %d | %s / %s |"
                         % (r["region_id"], "*(conditional)*" if r.get("conditional_on") else "",
                            r["side"], len(es),
                            "yes" if r["can_change_by_cut"] else "no",
                            "yes" if r["can_change_by_wash"] else "no"))
    return "\n".join(lines) + "\n"


def doc_measurements(spec, shots, ordered):
    lines = [BANNER, "# Measurement sheet", "",
             wrap("Each reading is taken INDEPENDENTLY: lay the tape again, do not copy the first "
                  "number. The point of two readings is their spread, and two copies of one reading "
                  "have a spread of zero and tell you nothing. Readings that disagree by more than "
                  "the tolerance block the cut."), "",
             wrap("Conventions, from `data/garments/*/record.json`: waist, thigh and leg opening are "
                  "FULL CIRCUMFERENCES (measured flat and doubled). Rise is from the crotch seam to "
                  "the top of the waistband along the fly. Inseam is crotch seam to hem along the "
                  "inside leg. Thigh is 2.5 cm below the crotch."), "",
             "| measurement | readings needed | tolerance | 1 | 2 | 3 | mean |",
             "|---|---|---|---|---|---|---|"]
    for name, n in sorted(GATES.REQUIRED_MEASUREMENTS.items()):
        tol = GATES.MEASUREMENT_TOLERANCE.get(name, GATES.MEASUREMENT_TOLERANCE["_default_cm"])
        cells = " | ".join(["______"] * n + [""] * (3 - n))
        lines.append("| `%s` | %d | %.2f | %s | ______ |" % (name, n, tol, cells))
    lines += ["", "## Post-wash, the same dimensions again", "",
              wrap("Shrinkage is the difference between two measurements, so the after-wash set is "
                   "taken the same way, twice each, by the same method. A dimension measured "
                   "carefully before and casually after produces a shrinkage figure that is mostly "
                   "the change in method."), ""]
    for name in sorted(GATES.REQUIRED_MEASUREMENTS):
        lines.append("- [ ] `%s` after wash: ______ / ______  mean ______" % name)
    return "\n".join(lines) + "\n"


def doc_cut_day(spec, shots, ordered):
    marked = [e for e in ordered if e["state"] == "marked"]
    return "\n".join([BANNER, "# Cut-day checklist", "",
        wrap("Do not start this page until `tools/pilot.py precut <GARMENT>` prints READY TO CUT. "
             "The cut is the irreversible step and everything before it exists to be recoverable."),
        "", "## Before you pick up the shears", "",
        "- [ ] `tools/pilot.py precut` prints READY TO CUT and lists no blocks",
        "- [ ] The printed cut packet is on the table (`tools/pilot.py packet <GARMENT> --out ...`)",
        "- [ ] Both offcut labels are written: `<GARMENT_ID>_OFFCUT_L` and `_R`, where L and R are "
        "the WEARER's left and right",
        "- [ ] The second person is here",
        "", "## Marking", "",
        wrap("The cut is a straight line PERPENDICULAR TO THE LEG'S CENTRE LINE through the inseam "
             "at the target length. It is NOT square to the inseam. Measure the target length down "
             "the inseam, and the target length PLUS the printed offset down the outseam, then join "
             "the two marks with the straightedge. On a leg tapering from a 60 cm thigh to a 40 cm "
             "opening that offset is about 18 mm; ignoring it cuts a line the software did not "
             "predict."), ""] +
        ["- [ ] `%s` — %s" % (e["shot_id"], e["framing"].split(".")[0]) for e in marked] +
        ["", "## Verification", "",
         "- [ ] Second person measures BOTH marks on BOTH legs with a tape",
         "- [ ] Every reading agrees with the packet within **%.0f mm**" % CUT.verification_tolerance_mm(),
         "- [ ] Verification recorded: `tools/pilot.py confirm <GARMENT> cut_marks_verified "
         "--verifier NAME --measured-inseam N --measured-outseam N`",
         "- [ ] Confirmed the legs will be cut SEPARATELY: `... confirm legs_cut_separately`",
         "- [ ] Confirmed the offcuts will be kept and labelled: `... confirm "
         "offcuts_retained_labelled`",
         "", "## Cutting", "",
         "- [ ] Legs cut one at a time, garment flat, one continuous stroke where possible",
         "- [ ] Cutting tool and operator name recorded",
         "- [ ] Both offcuts labelled IMMEDIATELY, before they leave the table",
         "- [ ] Any cutting irregularity noted and photographed",
         "", wrap("Once two offcuts are in two wash conditions, an unlabelled swap is unrecoverable "
                  "evidence loss. Label them before they move."), ""])


def doc_wash_day(spec, shots, ordered):
    return "\n".join([BANNER, "# Wash-day checklist", "",
        wrap("Planned settings and actual settings are recorded separately and the actual never "
             "replaces the planned. A deviation is the difference between the two, and it is only "
             "visible if both survive."), "",
        "## Before the load", "",
        "- [ ] Planned settings recorded: `tools/pilot.py wash <GARMENT>`",
        "- [ ] `tools/pilot.py gate ready_to_wash <GARMENT>` passes",
        "- [ ] Offcut wash assignment decided and recorded, alternating L/R against the previous "
        "garment",
        "- [ ] Filler load weighed or counted",
        "", "## Record for the actual run (`tools/pilot.py wash <GARMENT> --actual`)", ""] +
        ["- [ ] %s" % f for f in
         ("machine make/model", "location", "cycle name", "water temperature (C)", "spin (rpm)",
          "detergent brand", "detergent amount (ml)", "filler load", "start time", "end time",
          "dryer method", "dryer setting", "dryer duration (min)", "conditioning start",
          "conditioning end", "which samples were in this load")] +
        ["", wrap("Every field that differs from the plan becomes a recorded deviation "
                  "automatically. Do not 'fix' the plan to match what happened."), ""])


def doc_post_wash(spec, shots, ordered):
    pw = [e for e in ordered if e["state"] in ("post_wash", "offcut_after")]
    lines = [BANNER, "# Post-wash checklist", "",
             wrap("Conditioning first: lay flat at room temperature for the frozen conditioning "
                  "time before any measurement. A garment measured warm out of the dryer is not the "
                  "garment the protocol describes."), "",
             "- [ ] Conditioning time elapsed and recorded",
             "- [ ] All measurements taken again, twice each (see the measurement sheet)",
             "- [ ] Garment mass re-weighed",
             "", "## Frames (%d)" % len(pw), ""]
    for e in pw:
        lines.append("- [ ] `%s` (%d/%d)" % (e["shot_id"], e["rep"], e["rep_of"]))
    lines += ["", "## Hem mapping", "",
              wrap("The macro series has to cover the WHOLE loop of each cut hem with no gap. The "
                   "app's HEM tab shows which measurement positions are covered and which are not; "
                   "a gap there is a hole in the fray profile, not a rounding detail."), ""]
    for cm in (17, 20, 25):
        g = HEM.HemGeometry.from_leg_opening("left", cm)
        lines.append("- a %d cm leg opening is a %.0f mm loop: %d positions every %.0f mm, "
                     "%d macro frames" % (cm, g.circumference_mm, len(g.positions()),
                                          g.position_spacing_mm, len(g.macros())))
    return "\n".join(lines) + "\n"


def doc_offcut_labels(spec, shots, ordered):
    return "\n".join([BANNER, "# Offcut labels", "",
        wrap("Print or write these before cutting and keep them with the samples. L and R are the "
             "WEARER's left and right, which is the convention the region map and the app both use. "
             "Write the convention on the label itself: the person reading it in three weeks will "
             "not remember."), "",
        "```", "  +------------------------------------------+",
        "  |  <GARMENT_ID>_OFFCUT_L                   |",
        "  |  wearer's LEFT leg                       |",
        "  |  cut on ______________  by ____________  |",
        "  |  wash condition: ______________________  |",
        "  |  mass before ______ g   after ______ g   |",
        "  +------------------------------------------+", "",
        "  +------------------------------------------+",
        "  |  <GARMENT_ID>_OFFCUT_R                   |",
        "  |  wearer's RIGHT leg                      |",
        "  |  cut on ______________  by ____________  |",
        "  |  wash condition: ______________________  |",
        "  |  mass before ______ g   after ______ g   |",
        "  +------------------------------------------+", "```", "",
        wrap("The assignment alternates across garments: one offcut follows the standard protocol "
             "in the same load as the garment, the other is washed in a separate standard load. "
             "Which leg gets which swaps from garment to garment so the leg and the condition are "
             "not confounded. `tools/pilot.py offcut` records it."), ""])


def doc_recovery(spec, shots, ordered):
    return "\n".join([BANNER, "# Emergency recovery", "",
        wrap("Things that go wrong mid-session, and what to do about each. The general rule: the "
             "capture log is append-only and hash-chained, so the recovery is almost always to add "
             "a record rather than to edit one. Editing history breaks the chain and the gate will "
             "say so."), "",
        "## The laptop died mid-capture", "",
        wrap("Nothing is lost. The log is appended one line at a time and fsync'd, so at worst the "
             "final line is torn. The next run detects that, moves the torn bytes to "
             "`manifest.jsonl.torn`, and continues. Re-take the frame that was in flight; the app's "
             "NEXT ACTION will already be pointing at it."), "",
        "## A photograph is on the phone but not on the Mac", "",
        wrap("Re-transfer and add it again. Ingestion is content-addressed and idempotent: an "
             "identical file already present is recognised and not duplicated, and an interrupted "
             "copy is either completed or discovered to be complete."), "",
        "## I deleted a photograph by accident", "",
        wrap("The gate will block on `captures.files_intact` and name the file. Restore it from the "
             "phone (the hash in the manifest tells you whether you restored the right one), or "
             "re-take the frame. A manifest entry whose file is gone is not evidence."), "",
        "## The rig moved / the camera got knocked", "",
        wrap("Re-freeze it: `tools/pilot.py setup <GARMENT> --reason \"...\"`. This mints a NEW "
             "setup hash and records the change. Captures taken under the old hash stay valid and "
             "stay labelled with it; nothing is retroactively re-attributed. If the change was "
             "large enough to matter, re-take the frames that depended on it."), "",
        "## The board got bent, reprinted, or replaced", "",
        wrap("Re-measure the squares and record the reading. If the new print is out of tolerance, "
             "the gate blocks and it is right to: every scale derived from it would carry the "
             "error."), "",
        "## I answered an intake question wrongly", "",
        wrap("Answer it again. Feature answers are appended, and the latest wins. If the correction "
             "ADDS a feature, the plan grows and the new frames appear in NEXT ACTION. If it "
             "removes one, the frames you already took stay in the log and are simply no longer "
             "required."), "",
        "## The gate says READY and I do not believe it", "",
        wrap("Run `tools/pilot.py precut <GARMENT> --json /tmp/v.json` and read the satisfied list. "
             "Every condition names the evidence it accepted. If a condition passed that should not "
             "have, that is a defect in the gate and it is more important than the garment: stop, "
             "and add the case to `tools/pilot.py selftest`."), "",
        "## I cut the garment and something was missing", "",
        wrap("Record it as a deviation immediately, while you remember it. The offcuts carry a raw "
             "edge identical to the garment's, so some measurements can still be recovered from "
             "them. What cannot be recovered is a before-state photograph, which is the whole "
             "reason the gate exists."), ""])


#: One line per gate condition. Written here rather than derived from the code's docstrings because
#: the operator needs a sentence, not an implementation note -- but WHICH conditions appear is
#: derived by running the gate, so a condition added to gates.py cannot go unlisted. A condition
#: with no sentence here is a build failure rather than a silent omission.
CONDITION_LINES = {
    "spec.bound": "the session was opened under the shot plan that is on disk now",
    "log.intact": "the capture log's hash chain verifies, and it ends where its anchor says",
    "features.answered": "no unanswered question whose silence would drop a photograph",
    "plan.generated": "a shot plan could be generated at all from the answers given",
    "plan.fully_expanded": "every templated series was sized; none silently expanded to zero",
    "rig.frozen": "the rig configuration is frozen and hashed",
    "rig.calibrated": "every calibration reading recorded against THIS rig and explicitly passing",
    "rig.board_square_measured": "the printed squares measure 25.0 mm within 0.5, over a run of "
                                 "at least four whole squares",
    "rig.captures_attributable": "every photograph carries the rig hash in effect when it was taken",
    "rig.one_configuration": "the session used one rig, or the change is recorded as a deviation",
    "measurements.complete": "every measurement present, with its independent readings, in "
                             "tolerance and inside a plausible range",
    "captures.required_complete": "every required frame captured, checked, and passing",
    "captures.files_intact": "every recorded photograph on disk, hash unchanged, filed under its "
                             "own name inside the garment directory",
    "captures.relays_independent": "each repeat followed a real re-lay",
    "captures.repositions_recorded": "each repeat that needed a camera reposition records one",
    "captures.reuse_legitimate": "any reused image passed the borrowing shot's own checks",
    "captures.no_undeclared_reuse": "no photograph satisfies two shots without a declared reuse",
    "cut.specified": "the cut is defined and its outseam offset computed",
    "cut.second_person_verified": "a second person -- not the operator -- measured both marks "
                                  "within 3 mm, and did not refuse",
    "cut.confirmations": "legs cut separately, offcuts retained and labelled",
    "offcuts.assigned": "exactly two offcuts, one per leg, two defined conditions, the left/right "
                        "alternation intact across garments",
    "wash.planned": "a complete wash plan, written once and not revised",
    "wash.actual": "what actually happened, with every departure from the plan recorded",
}


def gate_condition_table(spec):
    """The conditions each gate actually names, discovered by running it.

    Listing them by hand is how the green sheet falls behind the gate, which is the one document
    where that must not happen.
    """
    import tempfile
    from denimtwin.pilot.store import Store

    rows, seen = [], set()
    for gate_id in ("ready_to_cut", "ready_to_wash", "ready_to_finalize"):
        tmp = Path(tempfile.mkdtemp()) / "DENIM_0000"
        v = GATES.evaluate(gate_id, spec, Store(tmp), garment_dir=tmp, check_files=False)
        names = sorted({b.condition for b in v.blocks}
                       | {x["condition"] for x in v.satisfied})
        fresh = [n for n in names if n not in seen]
        if not fresh:
            continue
        seen.update(fresh)
        if gate_id != "ready_to_cut":
            rows += ["", "`pilot.py gate %s` adds:" % gate_id, "",
                     "| condition | what must be true |", "|---|---|"]
        else:
            rows += ["| condition | what must be true |", "|---|---|"]
        for n in fresh:
            line = CONDITION_LINES.get(n)
            if line is None:
                raise SystemExit(
                    "gate condition %r has no sentence in make_runbook.CONDITION_LINES. The green "
                    "sheet is the one document that may not fall behind the gate; add a line for "
                    "it." % n)
            rows.append("| `%s` | %s |" % (n, line))
    return rows


def doc_green_sheet(spec, shots, ordered):
    req = [e for e in ordered if e["state"] in ("rig", "intake", "before", "marked")
           and e["necessity"] != "optional"]
    return "\n".join([BANNER, "# DO NOT CUT UNTIL THIS IS GREEN", "",
        "```",
        "        tools/pilot.py precut <GARMENT_ID>",
        "```", "",
        wrap("It must print READY TO CUT with no blocks. Anything else -- including a block whose "
             "message is that a condition could not be evaluated -- means do not cut. "
             "'We could not determine whether this is safe' is not permission."), "",
        "## What it is checking, in one line each", "",
    ] + gate_condition_table(spec) + [
wrap("On the most demanding garment the plan can describe, that is **%d required "
                 "frames** before the cut." % len(req)), "",
        "## The four results a photograph can get", "",
        "| result | meaning | what to do |", "|---|---|---|",
        "| **PASS** | the requirement is met and the evidence is recorded | next frame |",
        "| **RETAKE REQUIRED** | measurably not met | shoot it again |",
        "| **UNAVAILABLE CHECK** | the check could not run: no scale, no board, no dependency | "
        "supply what is missing. This is not a pass |",
        "| **HUMAN CHECK** | no measurement can settle it | look, and record what you saw |",
        "", wrap("None of the last three is a pass, and none of them can be cleared by ignoring it. "
                 "That is the whole point of the sheet."), ""])


DOCS = [
    ("PILOT_RUNBOOK.md", doc_runbook),
    ("CHECKLIST_EQUIPMENT.md", doc_equipment),
    ("CHECKLIST_RIG.md", doc_rig),
    ("SHOTLIST_ANATOMY.md", doc_anatomy),
    ("MEASUREMENT_SHEET.md", doc_measurements),
    ("CHECKLIST_CUT_DAY.md", doc_cut_day),
    ("CHECKLIST_WASH_DAY.md", doc_wash_day),
    ("CHECKLIST_POST_WASH.md", doc_post_wash),
    ("OFFCUT_LABELS.md", doc_offcut_labels),
    ("RECOVERY.md", doc_recovery),
    ("DO_NOT_CUT_UNTIL_GREEN.md", doc_green_sheet),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", default=str(ROOT / "protocol" / "pilot"))
    a = ap.parse_args()
    spec = SPEC.load(ROOT / "protocol" / "shotplan" / "shotplan.json")
    shots, ordered = build(spec)
    out = Path(a.out)
    stale, wrote = [], []
    for name, fn in DOCS:
        text = fn(spec, shots, ordered)
        p = out / name
        if a.check:
            if not p.exists() or p.read_text() != text:
                stale.append(name)
        if a.write:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
            wrote.append("%s (%d lines)" % (name, text.count("\n")))
    if a.check:
        if stale:
            print("stale or missing pilot documents: %s" % ", ".join(stale))
            print("regenerate with tools/make_runbook.py --write")
            return 1
        print("pilot documents: %d, all current" % len(DOCS))
        return 0
    for w in wrote:
        print("wrote", w)
    if not a.write:
        print("nothing written; pass --write or --check")
    return 0


if __name__ == "__main__":
    sys.exit(main())
